# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mostly Interesting, mostly
#email: chuckchiamb@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  A few things that seemed harder to find than others.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  chuckchiam

# Build settings
markdown: kramdown
highlighter: rouge
