title: Mostly Interesting, mostly
description: some things that took longer to find than some others

url: http://chuckchiamb.github.io
baseurl: ""
paginate_path: "page:num/"
permalink: :title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: chuckchiam
   #twitter: brianmaierjr
   #facebook: brianmaierjr
   #email: brimaidesigns@gmail.com

#google_analytics: "UA-58263416-1"
